language: node_js

stages:
  - name: test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      name: lint
      script:
        - npm run lint
    - stage: deploy
      name: Deploy Chrome
      script:
        - npm run build:chrome
        - ./node_modules/.bin/webstore upload \
            --source=build \
            --extension-id=
            --client-id=
            --client-secret=
            --refresh-token
            --auto-publish
            --trusted-testers
    - stage: deploy
      name: Deploy Firefox
      script:
        - npm run build:firefox
        - npm run web-ext:lint
        - ./node_modules/.bin/web-ext sign \
            --api-key= \
            --api-secret= \
